/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front_end;

import baylung.user_facts;
import java.util.HashMap;

/**
 *
 * @author Benny
 */
public class MainSyptom2 extends javax.swing.JFrame {
    HashMap<String,user_facts> WM = new HashMap<String,user_facts>();
    /**
     * Creates new form MainSyptom2
     */
    insertion insert = new insertion();
    public MainSyptom2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infiltrate = new javax.swing.ButtonGroup();
        pleura = new javax.swing.ButtonGroup();
        chest = new javax.swing.ButtonGroup();
        Ronchten = new javax.swing.ButtonGroup();
        diaphragma = new javax.swing.ButtonGroup();
        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Rontchenwhite = new javax.swing.JRadioButton();
        Ronchtenblack = new javax.swing.JRadioButton();
        rontchennormal = new javax.swing.JRadioButton();
        ChestMB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ChestMD = new javax.swing.JTextField();
        pleurayes = new javax.swing.JRadioButton();
        pleurano = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        LengthMB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LengthMD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        RibMB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        RibMD = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        diaphyes = new javax.swing.JRadioButton();
        diaphno = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        infiltratespread = new javax.swing.JRadioButton();
        infiltrategathered = new javax.swing.JRadioButton();
        infiltratenone = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        chestYes = new javax.swing.JRadioButton();
        ChestNo = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Rib Gap widened");

        jLabel2.setText("Lung Lengthwise");

        jLabel3.setText("Fluid in Pleura");

        jLabel4.setText("Scars on Lung");

        jLabel5.setText("Rontchen");

        Ronchten.add(Rontchenwhite);
        Rontchenwhite.setText("whitened out");

        Ronchten.add(Ronchtenblack);
        Ronchtenblack.setText("blacked out");

        Ronchten.add(rontchennormal);
        rontchennormal.setText("normal");

        jLabel6.setText("MB");

        jLabel7.setText("MD");

        pleura.add(pleurayes);
        pleurayes.setText("yes");
        pleurayes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pleurayesActionPerformed(evt);
            }
        });

        pleura.add(pleurano);
        pleurano.setText("no");

        jLabel8.setText("MB");

        jLabel9.setText("MD");

        jLabel10.setText("MB");

        jLabel11.setText("MD");

        jLabel12.setText("weight");

        jLabel13.setText("height");

        jLabel14.setText("flatten diaphragma");

        diaphragma.add(diaphyes);
        diaphyes.setText("yes");

        diaphragma.add(diaphno);
        diaphno.setText("no");

        jLabel15.setText("infiltrate");

        infiltrate.add(infiltratespread);
        infiltratespread.setText("spreaded");

        infiltrate.add(infiltrategathered);
        infiltrategathered.setText("gathered");

        infiltrate.add(infiltratenone);
        infiltratenone.setText("none");

        jLabel16.setText("chest scar");

        chest.add(chestYes);
        chestYes.setText("yes");

        chest.add(ChestNo);
        ChestNo.setText("no");

        jLabel17.setText("gender");

        gender.add(male);
        male.setText("male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        gender.add(female);
        female.setText("female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChestMB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChestMD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LengthMB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LengthMD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rontchenwhite)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Ronchtenblack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rontchennormal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(female))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(infiltratespread)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infiltrategathered)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infiltratenone))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RibMB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RibMD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pleurayes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pleurano))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chestYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChestNo))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diaphyes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diaphno)))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(infiltratespread)
                    .addComponent(infiltrategathered)
                    .addComponent(infiltratenone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RibMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(RibMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LengthMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(LengthMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pleurayes)
                    .addComponent(pleurano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(chestYes)
                    .addComponent(ChestNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ChestMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(ChestMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Rontchenwhite)
                    .addComponent(Ronchtenblack)
                    .addComponent(rontchennormal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(male)
                    .addComponent(female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(diaphyes)
                    .addComponent(diaphno))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton1.setText("RESULT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pleurayesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pleurayesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pleurayesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //infiltrate is it spreaded ,none ,or gathered
        if(infiltratespread.isSelected()){
             WM = insert.insert(WM, "20", 1);
        }else{
             WM = insert.insert(WM, "20", -1);
        }
        
        if(infiltrategathered.isSelected()){
             WM = insert.insert(WM, "36", 1);
        }else{
             WM = insert.insert(WM, "36", -1);
        }
        if(infiltratenone.isSelected()){
             WM = insert.insert(WM, "36", -1);
             WM = insert.insert(WM, "20", -1);
        }
        
        //Rib Gap widened?
        double MBRib = insert.text_input(RibMB.getText());
        double MDRib = insert.text_input(RibMD.getText());
        WM = insert.insert(WM, "29", insert.CFcalculate(MBRib, MDRib));
        
        //lung lengthwise?
        double MBLength = insert.text_input(LengthMB.getText());
        double MDLength = insert.text_input(LengthMD.getText());
        WM = insert.insert(WM, "22", insert.CFcalculate(MBLength, MDLength));
        
        //fluid in pleura
        if(pleurayes.isSelected()){
             WM = insert.insert(WM, "41", 1);
        }else{
             WM = insert.insert(WM, "41", -1);
        }
        
        //chest scar
        if(chestYes.isSelected()){
             WM = insert.insert(WM, "43", 1);
        }else{
             WM = insert.insert(WM, "43", -1);
        }
        
        //lung scars?
        double MBChest = insert.text_input(ChestMB.getText());
        double MDChest = insert.text_input(ChestMD.getText());
        WM = insert.insert(WM, "49", insert.CFcalculate(MBChest, MDChest));
        
        //roncthen layout
        if(Rontchenwhite.isSelected()){
             WM = insert.insert(WM, "40", 1);
        }else{
             WM = insert.insert(WM, "40", -1);
        }
        
        if(Rontchenwhite.isSelected()){
             WM = insert.insert(WM, "40", 1);
        }else{
             WM = insert.insert(WM, "40", -1);
        }
        
        if(Ronchtenblack.isSelected()){
             WM = insert.insert(WM, "44", 1);
        }else{
             WM = insert.insert(WM, "44", -1);
        }
        if(rontchennormal.isSelected()){
             WM = insert.insert(WM, "44", -1);
             WM = insert.insert(WM, "40", -1);
        }
        if(diaphyes.isSelected()){
             WM = insert.insert(WM, "50", 1);
        }else{
              WM = insert.insert(WM, "50", 1);
        }
        
        double idealweight;
        if(male.isSelected()){
            idealweight = 50+(2.3*(Double.parseDouble(height.getText())/4));
        }else{
            idealweight = 45.5+(2.3*(Double.parseDouble(height.getText())/4));
        }
        if(Double.parseDouble(weight.getText())<idealweight -(idealweight *(30/100)) ){
            WM = insert.insert(WM, "38", 1);
        }else{
            WM = insert.insert(WM, "38", -1);
        }
        
        System.out.println();
        for (HashMap.Entry<String, user_facts> entry : WM.entrySet()) {
            System.out.print("key=" + entry.getKey());
            for(int i = 0 ;i<entry.getValue().AU.size();i++){
                System.out.print("ID = "+entry.getValue().AU.get(i).id +" CF = "+entry.getValue().AU.get(i).CF+" " );
            }
            System.out.println();
        }
        
        Result res = new Result();
        res.WM = this.WM;
        res.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSyptom2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSyptom2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSyptom2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSyptom2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSyptom2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChestMB;
    private javax.swing.JTextField ChestMD;
    private javax.swing.JRadioButton ChestNo;
    private javax.swing.JTextField LengthMB;
    private javax.swing.JTextField LengthMD;
    private javax.swing.JTextField RibMB;
    private javax.swing.JTextField RibMD;
    private javax.swing.ButtonGroup Ronchten;
    private javax.swing.JRadioButton Ronchtenblack;
    private javax.swing.JRadioButton Rontchenwhite;
    private javax.swing.ButtonGroup chest;
    private javax.swing.JRadioButton chestYes;
    private javax.swing.JRadioButton diaphno;
    private javax.swing.ButtonGroup diaphragma;
    private javax.swing.JRadioButton diaphyes;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField height;
    private javax.swing.ButtonGroup infiltrate;
    private javax.swing.JRadioButton infiltrategathered;
    private javax.swing.JRadioButton infiltratenone;
    private javax.swing.JRadioButton infiltratespread;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.ButtonGroup pleura;
    private javax.swing.JRadioButton pleurano;
    private javax.swing.JRadioButton pleurayes;
    private javax.swing.JRadioButton rontchennormal;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
