/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front_end;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import baylung.*;
import java.util.HashMap;
/**
 *
 * @author Benny
 */
public class MainSyptom extends javax.swing.JFrame {
    HashMap<String,user_facts> WM = new HashMap<String,user_facts>();
    insertion insert = new insertion();
    /**
     * Creates new form MainSyptom
     */
    public MainSyptom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asma = new javax.swing.ButtonGroup();
        coughing = new javax.swing.ButtonGroup();
        bloody = new javax.swing.ButtonGroup();
        mucus = new javax.swing.ButtonGroup();
        jLabel32 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        Colour = new javax.swing.ButtonGroup();
        Sticky = new javax.swing.ButtonGroup();
        BTAmorning = new javax.swing.ButtonGroup();
        BTAfirst = new javax.swing.ButtonGroup();
        SecondBTA = new javax.swing.ButtonGroup();
        polution = new javax.swing.ButtonGroup();
        Sonor = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        cough = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        yescough = new javax.swing.JRadioButton();
        nocough = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        yesblood = new javax.swing.JRadioButton();
        noblood = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        freqMB = new javax.swing.JTextField();
        freqMD = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        weeks = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Mucusyes = new javax.swing.JRadioButton();
        MucusNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Colourpure = new javax.swing.JRadioButton();
        Colourunpure = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        muchMB = new javax.swing.JTextField();
        muchMD = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        morningpositive = new javax.swing.JRadioButton();
        morningnegative = new javax.swing.JRadioButton();
        firstBTApositive = new javax.swing.JRadioButton();
        firstBTAnegative = new javax.swing.JRadioButton();
        secondPositive = new javax.swing.JRadioButton();
        seconNegative = new javax.swing.JRadioButton();
        BTACheckbox = new javax.swing.JCheckBox();
        jLabel62 = new javax.swing.JLabel();
        stickyyes = new javax.swing.JRadioButton();
        stickyno = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        temperature = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        painMD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        painMB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        soreMD = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        soreMB = new javax.swing.JTextField();
        lossAptMD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lossAptMB = new javax.swing.JTextField();
        rashMD = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rashMB = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        headacheMB = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        headacheMD = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        alergyItchy = new javax.swing.JRadioButton();
        alergySneezee = new javax.swing.JRadioButton();
        alergyCough = new javax.swing.JRadioButton();
        alergyNone = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        smokeMB = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        smokeMD = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        polutionyes = new javax.swing.JRadioButton();
        polutionno = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        polutionMB = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        polutionMD = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        respiration = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        WheezingMD = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        WheezingMB = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Sonoryes = new javax.swing.JRadioButton();
        Sonorno = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        asthmaAnc = new javax.swing.JRadioButton();
        bronAncestor = new javax.swing.JRadioButton();
        Next = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        jLabel32.setText("MB");

        jTextField19.setText("jTextField2");

        jLabel33.setText("MD");

        jTextField20.setText("jTextField3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cough.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cough.setToolTipText("Cough");
        cough.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cough.setName("Cough"); // NOI18N

        jLabel2.setText("Cough");

        coughing.add(yescough);
        yescough.setText("yes");
        yescough.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yescoughActionPerformed(evt);
            }
        });

        coughing.add(nocough);
        nocough.setText("no");
        nocough.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocoughActionPerformed(evt);
            }
        });

        jLabel3.setText("bloody cough");

        bloody.add(yesblood);
        yesblood.setText("yes");
        yesblood.setEnabled(false);

        bloody.add(noblood);
        noblood.setText("no");
        noblood.setEnabled(false);
        noblood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobloodActionPerformed(evt);
            }
        });

        jLabel22.setText("uncertain frequency");

        jLabel23.setText("MB");

        freqMB.setEnabled(false);

        freqMD.setEnabled(false);

        jLabel24.setText("MD");

        jLabel25.setText("how long?");

        weeks.setEnabled(false);
        weeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeksActionPerformed(evt);
            }
        });

        jLabel26.setText("weeks");

        javax.swing.GroupLayout coughLayout = new javax.swing.GroupLayout(cough);
        cough.setLayout(coughLayout);
        coughLayout.setHorizontalGroup(
            coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coughLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coughLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(yescough)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nocough))
                    .addGroup(coughLayout.createSequentialGroup()
                        .addGroup(coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25))
                        .addGap(24, 24, 24)
                        .addGroup(coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coughLayout.createSequentialGroup()
                                .addComponent(weeks, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26))
                            .addGroup(coughLayout.createSequentialGroup()
                                .addComponent(yesblood)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noblood))
                            .addGroup(coughLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(freqMB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(freqMD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coughLayout.setVerticalGroup(
            coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coughLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yescough)
                    .addComponent(nocough))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yesblood)
                    .addComponent(noblood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(freqMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(freqMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coughLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(weeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Mucus");

        jLabel7.setText("much?");

        mucus.add(Mucusyes);
        Mucusyes.setText("yes");
        Mucusyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MucusyesActionPerformed(evt);
            }
        });

        mucus.add(MucusNo);
        MucusNo.setText("no");
        MucusNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MucusNoActionPerformed(evt);
            }
        });

        jLabel8.setText("Colour");

        Colour.add(Colourpure);
        Colourpure.setText("pure");
        Colourpure.setEnabled(false);

        Colour.add(Colourunpure);
        Colourunpure.setText("not pure");
        Colourunpure.setEnabled(false);
        Colourunpure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourunpureActionPerformed(evt);
            }
        });

        jLabel15.setText("MB");

        muchMB.setEnabled(false);

        muchMD.setEnabled(false);

        jLabel14.setText("MD");

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel42.setText("morning");

        jLabel43.setText("first visit");

        jLabel44.setText("second visit");

        BTAmorning.add(morningpositive);
        morningpositive.setText("positive");
        morningpositive.setEnabled(false);

        BTAmorning.add(morningnegative);
        morningnegative.setText("negative");
        morningnegative.setEnabled(false);

        BTAfirst.add(firstBTApositive);
        firstBTApositive.setText("positive");
        firstBTApositive.setEnabled(false);

        BTAfirst.add(firstBTAnegative);
        firstBTAnegative.setText("negative");
        firstBTAnegative.setEnabled(false);

        SecondBTA.add(secondPositive);
        secondPositive.setText("positive");
        secondPositive.setEnabled(false);

        SecondBTA.add(seconNegative);
        seconNegative.setText("negative");
        seconNegative.setEnabled(false);

        BTACheckbox.setText("BTA check");
        BTACheckbox.setEnabled(false);
        BTACheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTACheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(morningpositive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(morningnegative))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(secondPositive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seconNegative))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(firstBTApositive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstBTAnegative))))
                    .addComponent(BTACheckbox))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTACheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(morningpositive)
                    .addComponent(morningnegative))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(firstBTApositive)
                    .addComponent(firstBTAnegative))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(secondPositive)
                    .addComponent(seconNegative))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel62.setText("sticky");

        Sticky.add(stickyyes);
        stickyyes.setText("yes");
        stickyyes.setEnabled(false);

        Sticky.add(stickyno);
        stickyno.setText("no");
        stickyno.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Mucusyes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MucusNo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel62))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(stickyyes)
                                .addGap(18, 18, 18)
                                .addComponent(stickyno))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Colourpure)
                                .addGap(5, 5, 5)
                                .addComponent(Colourunpure))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(muchMB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(muchMD)))))
                .addGap(187, 187, 187)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Mucusyes)
                            .addComponent(MucusNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15)
                            .addComponent(muchMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(muchMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Colourpure)
                            .addComponent(Colourunpure))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel62)
                            .addComponent(stickyyes)
                            .addComponent(stickyno)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        temperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureActionPerformed(evt);
            }
        });

        jLabel10.setText("temperature");

        jLabel11.setText("pain all over the body");

        jLabel12.setText("MD");

        jLabel13.setText("MB");

        jLabel1.setText("rash on skin");

        jLabel4.setText("sore throat");

        jLabel5.setText("loss of appetite");

        jLabel16.setText("MD");

        jLabel17.setText("MB");

        jLabel18.setText("MD");

        jLabel19.setText("MB");

        jLabel20.setText("MD");

        jLabel21.setText("MB");

        jLabel38.setText("Headache");

        jLabel39.setText("MB");

        jLabel40.setText("MD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rashMB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addGap(18, 18, 18)
                                        .addComponent(headacheMB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(headacheMD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rashMD))))
                            .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(lossAptMB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(painMB)
                                            .addComponent(soreMB))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lossAptMD))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(soreMD))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(painMD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(painMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(painMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(soreMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soreMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel19)
                    .addComponent(lossAptMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(lossAptMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(headacheMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(headacheMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel21)
                    .addComponent(rashMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(rashMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Alergy");

        alergyItchy.setText("itchy");
        alergyItchy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergyItchyActionPerformed(evt);
            }
        });

        alergySneezee.setText("sneeze");

        alergyCough.setText("cough");
        alergyCough.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergyCoughActionPerformed(evt);
            }
        });

        alergyNone.setText("none");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alergyItchy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alergySneezee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alergyCough)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alergyNone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(alergyItchy)
                    .addComponent(alergySneezee)
                    .addComponent(alergyCough)
                    .addComponent(alergyNone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setText("smoking behaviour");

        jLabel28.setText("MB");

        jLabel29.setText("MD");

        jLabel45.setText("deal with polution daily");

        jLabel46.setText("use mask?");

        polution.add(polutionyes);
        polutionyes.setText("yes");

        polution.add(polutionno);
        polutionno.setText("no");

        jLabel47.setText("MB");

        jLabel48.setText("MD");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polutionyes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polutionno))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polutionMB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polutionMD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smokeMB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smokeMD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(smokeMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(smokeMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47)
                        .addComponent(polutionMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel48)
                        .addComponent(polutionMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(polutionyes)
                    .addComponent(polutionno))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel30.setText("respiration");

        jLabel31.setText("times/minutes");

        jLabel35.setText("MD");

        jLabel34.setText("MB");

        jLabel36.setText("wheezing");

        jLabel37.setText("Sonor");

        Sonor.add(Sonoryes);
        Sonoryes.setText("yes");
        Sonoryes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SonoryesActionPerformed(evt);
            }
        });

        Sonor.add(Sonorno);
        Sonorno.setText("no");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Sonoryes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sonorno))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WheezingMB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WheezingMD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(respiration, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(respiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel34)
                    .addComponent(WheezingMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(WheezingMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(Sonoryes)
                    .addComponent(Sonorno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel41.setText("ancestors have");

        asthmaAnc.setText("asthma");

        bronAncestor.setText("bronchitis");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(asthmaAnc))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(bronAncestor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(asthmaAnc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bronAncestor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Next.setText("NEXT");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Reset.setText("RESET");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cough, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 57, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reset)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cough, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next)
                    .addComponent(Reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yescoughActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yescoughActionPerformed
        // TODO add your handling code here:
        yesblood.setEnabled(true);
        noblood.setEnabled(true);
        freqMB.setEnabled(true);
        freqMD.setEnabled(true);
        weeks.setEnabled(true);
        
    }//GEN-LAST:event_yescoughActionPerformed

    private void nobloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nobloodActionPerformed

    private void nocoughActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocoughActionPerformed
        // TODO add your handling code here:
        yesblood.setEnabled(false);
        noblood.setEnabled(false);
        freqMB.setEnabled(false);
        freqMD.setEnabled(false);
        weeks.setEnabled(false);
    }//GEN-LAST:event_nocoughActionPerformed

    private void MucusyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MucusyesActionPerformed
        // TODO add your handling code here:
        muchMB.setEnabled(true);
        muchMD.setEnabled(true);
        Colourpure.setEnabled(true);
        Colourunpure.setEnabled(true);
        stickyyes.setEnabled(true);
        stickyno.setEnabled(true);
        BTACheckbox.setEnabled(true);
    }//GEN-LAST:event_MucusyesActionPerformed

    private void ColourunpureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourunpureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColourunpureActionPerformed

    private void temperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureActionPerformed

    private void alergyItchyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergyItchyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergyItchyActionPerformed

    private void alergyCoughActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergyCoughActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergyCoughActionPerformed

    private void weeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeksActionPerformed

    private void SonoryesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SonoryesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SonoryesActionPerformed

    private void MucusNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MucusNoActionPerformed
        // TODO add your handling code here:
        muchMB.setEnabled(false);
        muchMD.setEnabled(false);
        Colourpure.setEnabled(false);
        Colourunpure.setEnabled(false);
        stickyyes.setEnabled(false);
        stickyno.setEnabled(false);
        BTACheckbox.setEnabled(false);
    }//GEN-LAST:event_MucusNoActionPerformed

    private void BTACheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTACheckboxActionPerformed
        // TODO add your handling code here:
        if(BTACheckbox.isSelected()){
            morningpositive.setEnabled(true);
            morningnegative.setEnabled(true);
            firstBTApositive.setEnabled(true);
            firstBTAnegative.setEnabled(true);
            secondPositive.setEnabled(true);
            seconNegative.setEnabled(true);
        }
        else{
            morningpositive.setEnabled(false);
            morningnegative.setEnabled(false);
            firstBTApositive.setEnabled(false);
            firstBTAnegative.setEnabled(false);
            secondPositive.setEnabled(false);
            seconNegative.setEnabled(false);
        }
    }//GEN-LAST:event_BTACheckboxActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        
        //bloody cough?
        if(yesblood.isSelected()){
            WM = insert.insert(WM,"37",1,true);
        }else{
            WM = insert.insert(WM,"37",-1,true);
        }
        if (yescough.isSelected()){
            //calculate the certainty of frequent cough
            double MBfreq;
            double MDfreq;
            if(freqMB.getText() == " "){
                MBfreq = 0;
            }else{
                MBfreq = Double.parseDouble(freqMB.getText());
            }
            if(freqMD.getText() == " "){
                MDfreq = 0;
            }else{
                MDfreq = Double.parseDouble(freqMD.getText());
            }
            WM = insert.insert(WM, "11", insert.CFcalculate(MBfreq, MDfreq),true);
        
            //howlong?
            if(weeks.getText() != " " && Integer.parseInt(weeks.getText())>= 2){
                WM = insert.insert(WM, "35", insert.CFcalculate(MBfreq, MDfreq),true);
            }else{
                WM = insert.insert(WM, "35", 0,true);
            }
        }else{
            WM = insert.insert(WM, "35", -1,true);
            WM = insert.insert(WM, "11", -1,true);
        }
        
        
        //how much mucus
        
      
            
        
        double MBmuch;
        double MDmuch;
        if(Mucusyes.isSelected()){
            if(muchMB.getText() == " "){
            MBmuch = 0;
            }else{
                MBmuch = Double.parseDouble(muchMB.getText());
            }
            if(muchMD.getText() == " "){
                MDmuch = 0;
            }else{
                MDmuch = Double.parseDouble(muchMD.getText());
            }
            WM = insert.insert(WM, "16", insert.CFcalculate(MBmuch, MDmuch),true);
        }else{
            WM = insert.insert(WM, "16", -1,true);  
        }
        
        //sticky mucus?
        if(stickyyes.isSelected()){
            WM = insert.insert(WM, "13", 1,true);
        }else{
            WM = insert.insert(WM, "13", -1,true);
        }
        
        //colour mucus
        if(Colourunpure.isSelected()){
            WM = insert.insert(WM, "19", 1,true);
        }else{
            WM = insert.insert(WM, "19", -1,true);
        }
        
        //BTAcheck
        if(BTACheckbox.isSelected()){
            if(morningpositive.isSelected()){
                WM = insert.insert(WM, "31", 1,true);
            }else{
                WM = insert.insert(WM, "31", -1,true);
            }
            if(firstBTApositive.isSelected()){
                WM = insert.insert(WM, "32", 1,true);
            }else{
                WM = insert.insert(WM, "32", -1,true);
            }
            if(secondPositive.isSelected()){
                WM = insert.insert(WM, "33", 1,true);
            }else{
                WM = insert.insert(WM, "33", -1,true);
            }
        }else{
            WM = insert.insert(WM, "31", -1,true);
            WM = insert.insert(WM, "32", -1,true);
            WM = insert.insert(WM, "33", -1,true);
        }
        
        //temperature measurement
        
        if(temperature.getText() != "" && Double.parseDouble(temperature.getText())>=37){
            WM = insert.insert(WM, "6", 1,true);
        }else{
            WM = insert.insert(WM, "6", -1,true);
        }
        
        //pain in the body?
        double MBpain;
        double MDpain;
        if(painMB.getText() == " "){
            MBpain = 0;
        }else{
            MBpain = Double.parseDouble(painMB.getText());
        }
        if(painMD.getText() == " "){
            MDpain = 0;
        }else{
            MDpain = Double.parseDouble(painMD.getText());
         }
        WM = insert.insert(WM, "47", insert.CFcalculate(MBpain, MDpain),true);
        
        //sore throat?
        double MBsore;
        double MDsore;
        if(soreMB.getText() == " "){
            MBsore = 0;
        }else{
            MBsore = Double.parseDouble(soreMB.getText());
        }
        if(soreMD.getText() == " "){
            MDsore = 0;
        }else{
            MDsore = Double.parseDouble(soreMD.getText());
         }
        WM = insert.insert(WM, "7", insert.CFcalculate(MBsore, MDsore),true);
        
        //loss appetite?
        
        double MBlossApt;
        double MDlossApt;
        if(lossAptMB.getText() == " "){
            MBlossApt = 0;
        }else{
            MBlossApt = Double.parseDouble(lossAptMB.getText());
        }
        if(lossAptMD.getText() == " "){
            MDlossApt = 0;
        }else{
            MDlossApt = Double.parseDouble(lossAptMD.getText());
        }
        WM = insert.insert(WM, "8", insert.CFcalculate(MBlossApt, MDlossApt),true);
        
        //headache
        double MBheadache = insert.text_input(headacheMB.getText());
        double MDheadache = insert.text_input(headacheMD.getText());
        WM = insert.insert(WM, "5", insert.CFcalculate(MBheadache, MDheadache),true);
        
        //rash on skin?
        double MBrash = insert.text_input(rashMB.getText());
        double MDrash = insert.text_input(rashMD.getText());
        WM = insert.insert(WM, "9", insert.CFcalculate(MBrash, MDrash),true);
        
        //alergy
        if(alergyItchy.isSelected()){
            WM = insert.insert(WM, "1", 1,true);
        }else{
             WM = insert.insert(WM, "1", -1,true);
        }
        
        if(alergySneezee.isSelected()){
            WM = insert.insert(WM, "2", 1,true);
        }else{
             WM = insert.insert(WM, "2", -1,true);
        }
        
        if(alergyCough.isSelected()){
            WM = insert.insert(WM, "46", 1,true);
        }else{
             WM = insert.insert(WM, "46", -1,true);
        }
        
        //smoke often?
        double MBsmoke = insert.text_input(smokeMB.getText());
        double MDsmoke = insert.text_input(smokeMD.getText());
        WM = insert.insert(WM, "26", insert.CFcalculate(MBsmoke, MDsmoke),true);
        
        //polution
        double MBpolution = insert.text_input(polutionMB.getText());
        double MDpolution = insert.text_input(polutionMD.getText());
        WM = insert.insert(WM, "49", insert.CFcalculate(MBpolution, MDpolution),true);
        
        //mask
        if(polutionyes.isSelected()){
             WM = insert.insert(WM, "48", 1,true);
        }else{
             WM = insert.insert(WM, "48", -1,true);
        }
        
        //difficulty of brathing
        double respirationDoub = insert.text_input(respiration.getText());
        if(respirationDoub  < 26){
            WM = insert.insert(WM, "12", 1,true);
        }else{
            WM = insert.insert(WM, "12", -1,true);
        }
        double MBWheezing = insert.text_input(WheezingMB.getText());
        double MDWheezing = insert.text_input(WheezingMD.getText());
        WM = insert.insert(WM, "10", insert.CFcalculate(MBWheezing, MDWheezing),true);
        
        //Hipersonor?
        
        if(Sonoryes.isSelected()){
             WM = insert.insert(WM, "23", 1,true);
        }else{
             WM = insert.insert(WM, "23", -1,true);
        }
        
        //ancestor
        if(asthmaAnc.isSelected()){
             WM = insert.insert(WM, "15", 1,true);
        }else{
             WM = insert.insert(WM, "15", -1,true);
        }
        if(bronAncestor.isSelected()){
             WM = insert.insert(WM, "17", 1,true);
        }else{
             WM = insert.insert(WM, "17", -1,true);
        }
        
        
        
        
        for (HashMap.Entry<String, user_facts> entry : WM.entrySet()) {
            System.out.print("key=" + entry.getKey());
            for(int i = 0 ;i<entry.getValue().AU.size();i++){
                System.out.print("ID = "+entry.getValue().AU.get(i).id +" CF = "+entry.getValue().AU.get(i).CF+" " );
            }
            System.out.println();
        }   
        
        MainSyptom2 syp = new MainSyptom2();
        syp.WM = this.WM;
        syp.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSyptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSyptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSyptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSyptom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSyptom().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BTACheckbox;
    private javax.swing.ButtonGroup BTAfirst;
    private javax.swing.ButtonGroup BTAmorning;
    private javax.swing.ButtonGroup Colour;
    private javax.swing.JRadioButton Colourpure;
    private javax.swing.JRadioButton Colourunpure;
    private javax.swing.JRadioButton MucusNo;
    private javax.swing.JRadioButton Mucusyes;
    private javax.swing.JButton Next;
    private javax.swing.JButton Reset;
    private javax.swing.ButtonGroup SecondBTA;
    private javax.swing.ButtonGroup Sonor;
    private javax.swing.JRadioButton Sonorno;
    private javax.swing.JRadioButton Sonoryes;
    private javax.swing.ButtonGroup Sticky;
    private javax.swing.JTextField WheezingMB;
    private javax.swing.JTextField WheezingMD;
    private javax.swing.JRadioButton alergyCough;
    private javax.swing.JRadioButton alergyItchy;
    private javax.swing.JRadioButton alergyNone;
    private javax.swing.JRadioButton alergySneezee;
    private javax.swing.ButtonGroup asma;
    private javax.swing.JRadioButton asthmaAnc;
    private javax.swing.ButtonGroup bloody;
    private javax.swing.JRadioButton bronAncestor;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JPanel cough;
    private javax.swing.ButtonGroup coughing;
    private javax.swing.JRadioButton firstBTAnegative;
    private javax.swing.JRadioButton firstBTApositive;
    private javax.swing.JTextField freqMB;
    private javax.swing.JTextField freqMD;
    private javax.swing.JTextField headacheMB;
    private javax.swing.JTextField headacheMD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField lossAptMB;
    private javax.swing.JTextField lossAptMD;
    private javax.swing.JRadioButton morningnegative;
    private javax.swing.JRadioButton morningpositive;
    private javax.swing.JTextField muchMB;
    private javax.swing.JTextField muchMD;
    private javax.swing.ButtonGroup mucus;
    private javax.swing.JRadioButton noblood;
    private javax.swing.JRadioButton nocough;
    private javax.swing.JTextField painMB;
    private javax.swing.JTextField painMD;
    private javax.swing.ButtonGroup polution;
    private javax.swing.JTextField polutionMB;
    private javax.swing.JTextField polutionMD;
    private javax.swing.JRadioButton polutionno;
    private javax.swing.JRadioButton polutionyes;
    private javax.swing.JTextField rashMB;
    private javax.swing.JTextField rashMD;
    private javax.swing.JTextField respiration;
    private javax.swing.JRadioButton seconNegative;
    private javax.swing.JRadioButton secondPositive;
    private javax.swing.JTextField smokeMB;
    private javax.swing.JTextField smokeMD;
    private javax.swing.JTextField soreMB;
    private javax.swing.JTextField soreMD;
    private javax.swing.JRadioButton stickyno;
    private javax.swing.JRadioButton stickyyes;
    private javax.swing.JTextField temperature;
    private javax.swing.JTextField weeks;
    private javax.swing.JRadioButton yesblood;
    private javax.swing.JRadioButton yescough;
    // End of variables declaration//GEN-END:variables
}
